name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.4
  build: ^1.2.2
  code_builder: ^3.2.1
  collection: ^1.14.12
  dart_style: ^1.3.3
  logging: ^0.11.4
  meta: ^1.1.8
  path: ^1.6.4
  quiver: ^2.1.2+1
  stack_trace: ^1.9.3

dev_dependencies:
  build_runner: ^1.7.4
  build_test: ^0.10.12+1
  inject:
    path: ../inject
  test: ^1.12.0
